travis:
  secure:
    BINSTAR_TOKEN: S8D0lJJUblixWS057UGicZwbor8bTlj9VmV735rAlH78q/FU471aYdooAcafnfGaznoSxtHlk8j4fJ4mmyQ/Rkc+tAk5fojSTMZQK33l5FpXk0Ov0hOCzMLWCHshLDRlOK7iuKUjzDDe+VrjE1GwPXvAyjJOLrgl1ViIcSnZpq7J2ygZVdwqGjuIOnYWV07Tqd3Pfk2SThSuzvD1XBW0mQTzZxQygtYAGmATBe5+WiUb7CVjpXab++WS3HcNN/T50fCqCziljgns696qZOrnCs/KdaFCIHb3QHuO7Kb3AdC2vUU0TKrKkHbASmveEeXkPdqUex7uZV/w9uTEYf+M3x1uf6TXJ6ZBUBTFFx/RxHSRRgQmaIFxfcaQL33yJaNImQll3m9SKeyuYwoX9HEMd9Em/mljsY4+fk3oVo6bNhmvrxsCQxqcoTLf4iGMG2uoEv8ZGMKWvOydnI1kWrHtZ3lyZBnZEnOFu/QRLEtMeibLMoPCw9MQgRr9UxwFtCKBc18rzJZYH4+G39HXhLQYaqlOJzzFQtswovQZHY7EI9/JIbkBwmvXRgQJHOTdoN8sPYUF/6ylZPzuzkNBH8+jHLBJYrdIkGzj7YjV5r0zhgzdBl1h4pbK/HusIbGBL8h1773DUfa+DibTr0LyAy381bWfThwpDZ0XaJdmkxS0TvI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
